services:
  mysql:
    image: mysql:8.0
    container_name: knittda-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: knittda-db
      MYSQL_USER: user
      MYSQL_PASSWORD: a123456789!
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knittda-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://knittda-mysql:3306/knittda-db?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: a123456789!
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET_KEY: my_secret_key_1234567890
      SPRINGDOC_API_DOCS_PATH: /api-docs
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui/index.html
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: always