version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: knittda-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: knittda-db
      MYSQL_USER: user
      MYSQL_PASSWORD: a123456789!
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
